[project]
name = "docling-serve-rocm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "pytorch-triton-rocm",
    "docling-serve[ui]",
]

[tool.uv.sources]
